# Generated by Django 2.2.3 on 2019-07-23 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='word',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='word', to='content.Tag'),
        ),
        migrations.AddField(
            model_name='word',
            name='translation_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_translation', to='content.Word'),
        ),
    ]
